# Generated by Django 5.0.3 on 2024-03-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='products')),
                ('photoTwo', models.ImageField(upload_to='products')),
                ('photoThree', models.ImageField(upload_to='products')),
                ('photoFour', models.ImageField(upload_to='products')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('man', models.BooleanField(default=False)),
                ('women', models.BooleanField(default=False)),
                ('accessories', models.BooleanField(default=False)),
                ('Others', models.BooleanField(default=False)),
            ],
        ),
    ]
