# Generated by Django 5.0.3 on 2024-03-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cod',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='insideDhaka',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='online',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='outsideDhaka',
            field=models.BooleanField(null=True),
        ),
    ]
