# Generated by Django 5.0.3 on 2024-03-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_orders_cod_alter_orders_insidedhaka_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='items_json',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
