# Generated by Django 5.0.3 on 2024-03-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_orders_items_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
