# Generated by Django 5.0.3 on 2024-04-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_orders_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='country',
            new_name='thana',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='cod',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='insideDhaka',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='outsideDhaka',
        ),
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='online',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='COD',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
