# Generated by Django 5.0.3 on 2024-04-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_firstname_orders_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='COD',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='online',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
