# Generated by Django 5.0.3 on 2024-04-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_orders_cod_alter_orders_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='COD',
            new_name='CashOnDelivary',
        ),
        migrations.AddField(
            model_name='orders',
            name='OederPlaced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='Total_Payment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='online_Sender_phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='online_transaction_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items_json',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='orders',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='thana',
            field=models.CharField(max_length=100),
        ),
    ]
