# Generated by Django 5.0.3 on 2024-04-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_cod_orders_cashondelivary_orders_oederplaced_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='orders',
            name='items_json',
        ),
        migrations.AddField(
            model_name='orders',
            name='items_list',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='orders',
            name='CashOnDelivary',
            field=models.CharField(default='null', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='email',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='online',
            field=models.CharField(default='null', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='online_Sender_phone_number',
            field=models.CharField(default='null', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='online_transaction_id',
            field=models.CharField(default='null', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='state',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='thana',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
