# Generated by Django 5.0.3 on 2024-04-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_orders_online_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.ImageField(upload_to='banners')),
                ('headline', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=50)),
                ('offer', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='online_transaction_id',
            field=models.CharField(default='null', max_length=20, null=True),
        ),
    ]
