# Generated by Django 5.0.3 on 2024-04-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_shopinfo_alter_banner_content_alter_banner_headline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='content',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='headline',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='offer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
