# Generated by Django 4.1.7 on 2024-04-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_products_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='dummyPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='inStock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='onlinePaymentNumber',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
